using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace inkvBE.Migrations
{
    /// <inheritdoc />
    public partial class TypeSeeding4 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "Types",
                columns: new string[] { "Id", "TypeName", "SubcategoryId" },
                values: new object[,]
                {
                    { 481, "Apgyvendinimas", 66 },
                    { 482, "Įrangos nuoma", 66 },
                    { 483, "Kaimo turizmas", 66 },
                    { 484, "Kelionės Lietuvoje, žygiai", 66 },
                    { 485, "Kelionės užsienyje", 66 },
                    { 486, "Pramogos", 66 },
                    { 487, "Turizmo prekės", 66 },
                    { 488, "Kita", 66 },
                    { 489, "Mergina ieško vaikino", 67 },
                    { 490, "Vaikinas ieško merginos", 67 },
                    { 491, "Vaikinas ieško vaikino", 67 },
                    { 492, "Medžioklės reikmenys", 68 },
                    { 493, "Žvejybos reikmenys", 68 },
                    { 494, "Trofėjai", 68 },
                    { 495, "Ginklai", 68 },
                    { 496, "Paslaugos", 68 },
                    { 497, "Muzikos instrumentai", 69 },
                    { 498, "Muzikos įrašai", 69 },
                    { 499, "Paslaugos", 69 },
                    { 500, "Kita", 69 },
                    { 501, "Į kavinę, restoraną", 70 },
                    { 502, "Į kiną", 70 },
                    { 503, "Į klubą", 70 },
                    { 504, "Į koncertą", 70 },
                    { 505, "Į parodą", 70 },
                    { 506, "Į sporto renginį", 70 },
                    { 507, "Į teatrą", 70 },
                    { 508, "Kita", 70 },
                    { 509, "Erotiniai žaislai", 71 },
                    { 510, "Kontracepcijos priemonės", 71 },
                    { 511, "Lubrikantai, aliejai", 71 },
                    { 512, "Seksualūs rūbai", 71 },
                    { 513, "Šokėjai", 71 },
                    { 514, "Kita", 71 },
                    { 515, "Apatinis trikotažas", 73 },
                    { 516, "Chalatai", 73 },
                    { 517, "Kailiniai", 73 },
                    { 518, "Kelnės", 73 },
                    { 519, "Kepurės, skrybėlės", 73 },
                    { 520, "Kojinės, pėdkelnės", 73 },
                    { 521, "Kombinezonai", 73 },
                    { 522, "Kostiumėliai", 73 },
                    { 523, "Liemenės", 73 },
                    { 524, "Marškinėliai", 73 },
                    { 525, "Marškiniai", 73 },
                    { 526, "Maudymukai", 73 },
                    { 527, "Kita", 73 },
                    { 528, "Apatinis trikotažas", 74 },
                    { 529, "Chalatai", 74 },
                    { 530, "Glaudės, maudymosi šortai", 74 },
                    { 531, "Kailiniai", 74 },
                    { 532, "Kaklaraiščiai, peteliškės", 74 },
                    { 533, "Kelnės", 74 },
                    { 534, "Kepurės, skrybėlės", 74 },
                    { 535, "Kojinės", 74 },
                    { 536, "Kombinezonai", 74 },
                    { 537, "Kostiumai", 74 },
                    { 538, "Kita", 74 },
                    { 539, "Kūdikiams (iki 1 metų)", 75 },
                    { 540, "Berniukams", 75 },
                    { 541, "Mergaitėms", 75 },
                    { 542, "Kita", 75 },
                    { 543, "Vyrams", 76 },
                    { 544, "Moterims", 76 },
                    { 545, "Vaikams", 76 },
                    { 546, "Priežiūros priemonės", 76 },
                    { 547, "Dovanojama avalynė", 76 },
                    { 548, "Kita", 76 },
                    { 549, "Darbinė apranga", 77 },
                    { 550, "Karnavalinė apranga", 77 },
                    { 551, "Medžioklės apranga", 77 },
                    { 552, "Tautiniai kostiumai", 77 },
                    { 553, "Žvejybos apranga", 77 },
                    { 554, "Akiniai", 78 },
                    { 555, "Diržai, petnešos", 78 },
                    { 556, "Krepšiai, lagaminai", 78 },
                    { 557, "Laikrodžiai", 78 },
                    { 558, "Papuošalai", 78 },
                    { 559, "Perukai, šinjonai", 78 },
                    { 560, "Piniginės", 78 },
                    { 561, "Raktų pakabukai", 78 },
                    { 562, "Rankinės", 78 },
                    { 563, "Sąsagos", 78 },
                    { 564, "Skėčiai", 78 },
                    { 565, "Žiebtuvėliai", 78 },
                    { 566, "Vaikiški aksesuarai", 78 },
                    { 567, "Kita", 78 },
                    { 568, "Didmeninė prekyba", 79 },
                    { 569, "Drabužių taisymas", 79 },
                    { 570, "Laikrodžių, juvelyrikos taisymas", 79 },
                    { 571, "Nuoma", 79 },
                    { 572, "Siuvimas", 79 },
                    { 573, "Avalynės taisymas", 79 },
                    { 574, "Kita", 79 },
                    { 575, "Drabužiai", 81 },
                    { 576, "Avalynė", 81 },
                    { 577, "Papuošalai, aksesuarai", 81 },
                    { 578, "Dovanojami drabužėliai, avalynė", 81 },
                    { 579, "Kėdutės", 82 },
                    { 580, "Komodos", 82 },
                    { 581, "Lovytės, čiužiniai", 82 },
                    { 582, "Maniežai", 82 },
                    { 583, "Spintos", 82 },
                    { 584, "Stalai", 82 },
                    { 585, "Vaikų kambario lovos", 82 },
                    { 586, "Varteliai, tvorelės", 82 },
                    { 587, "Lauko baldai", 82 },
                    { 588, "Komplektai", 82 },
                    { 589, "Kita", 82 },
                    { 590, "Higienos prekės", 83 },
                    { 591, "Maistas, indai", 83 },
                    { 592, "Maitinimo pagalvės", 83 },
                    { 593, "Mobiliosios auklės", 83 },
                    { 594, "Patalynė", 83 },
                    { 595, "Pientraukiai", 83 },
                    { 596, "Kita", 83 },
                    { 597, "Autokėdutės", 84 },
                    { 598, "Vežimėliai", 84 },
                    { 599, "Gultukai, sūpynės", 85 },
                    { 600, "Kūdikių nešynės", 85 },
                    { 601, "Mini automobiliai, motociklai", 85 },
                    { 602, "Paspirtukai", 85 },
                    { 603, "Rogės, rogutės", 85 },
                    { 604, "Šokliukai", 85 },
                    { 605, "Triratukai", 85 },
                    { 606, "Vaikiški dviračiai", 85 },
                    { 607, "Vaikštynės, stumdukai", 85 },
                    { 608, "Dviračio kėdutės, priekabos", 85 },
                    { 609, "Kita", 85 },
                    { 610, "Mokyklinės prekės", 86 },
                    { 611, "Žaislai", 86 },
                    { 612, "Būreliai, stovyklos", 87 },
                    { 613, "Pramogos vaikams", 87 },
                    { 614, "Vaikiškos įrangos nuoma", 87 },
                    { 615, "Vaikiškų drabužių nuoma", 87 },
                    { 616, "Vaikų priežiūra", 87 }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
