using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace inkvBE.Migrations
{
    /// <inheritdoc />
    public partial class TypeSeeding3 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "Types",
                columns: new string[] { "Id", "TypeName", "SubcategoryId" },
                values: new object[,]
                {
                    { 351, "Alcatel", 49 },
                    { 352, "Anycool", 49 },
                    { 353, "Apple", 49 },
                    { 354, "Asus", 49 },
                    { 355, "BlackBerry", 49 },
                    { 356, "Blackview", 49 },
                    { 357, "Caterpillar", 49 },
                    { 358, "Cubot", 49 },
                    { 359, "Doogee", 49 },
                    { 360, "Doro", 49 },
                    { 361, "eSTAR", 49 },
                    { 362, "Fonos", 49 },
                    { 363, "Getnord", 49 },
                    { 364, "Google", 49 },
                    { 365, "HTC", 49 },
                    { 366, "Huawei", 49 },
                    { 367, "Lenovo", 49 },
                    { 368, "LG", 49 },
                    { 369, "Kita", 49},
                    { 370, "Akumuliatoriai", 52 },
                    { 371, "Atminties kortelės", 52 },
                    { 372, "Automobiliniai laikikliai", 52 },
                    { 373, "Dėklai", 52 },
                    { 374, "Išmanieji laikrodžiai", 52 },
                    { 375, "Įkrovikliai", 52 },
                    { 376, "Kolonėlės", 52 },
                    { 377, "Korpusai, ekranai, plėvelės", 52 },
                    { 378, "Laidai, jungtys", 52 },
                    { 379, "Laisvų rankų įranga", 52 },
                    { 380, "Kita", 52 },
                    { 381, "GPS remontas, atnaujinimas", 53 },
                    { 382, "Supirkimas", 53 },
                    { 383, "Telefonų remontas", 53 },
                    { 384, "Kita", 53 },
                    { 385, "Ausinės", 55 },
                    { 386, "Ausinukai", 55 },
                    { 387, "CD, DVD grotuvai", 55 },
                    { 388, "Diktofonai", 55 },
                    { 389, "Karaoke sistemos", 55 },
                    { 390, "Kolonėlės", 55 },
                    { 391, "Mikrofonai", 55 },
                    { 392, "MP3, MP4 grotuvai", 55 },
                    { 393, "Muzikiniai centrai", 55 },
                    { 394, "Plokštelių grotuvai", 55 },
                    { 395, "Radijo imtuvai", 55 },
                    { 396, "Stiprintuvai", 55 },
                    { 397, "Tinklo grotuvai", 55 },
                    { 398, "Automagnetolos", 55 },
                    { 399, "Magnetolos", 55 },
                    { 400, "Garso įranga", 55 },
                    { 401, "Kita", 55 },
                    { 402, "Televizoriai ir priedai", 56 },
                    { 403, "Namų kinas", 56 },
                    { 404, "Palydoviniai imtuvai", 56 },
                    { 405, "Skaitmeniniai imtuvai", 56 },
                    { 406, "Vaizdo grotuvai", 56 },
                    { 407, "Vaizdo kameros", 56 },
                    { 408, "Dalys, priedai", 56 },
                    { 409, "Kita", 56 },
                    { 410, "Smulki buitinė technika", 57 },
                    { 411, "Daugiafunkciniai puodai", 57 },
                    { 412, "Drėgmės surinktuvai", 57 },
                    { 413, "Dulkių siurbliai", 57 },
                    { 414, "Džiovyklės", 57 },
                    { 415, "Garais valantys prietaisai", 57 },
                    { 416, "Gartraukiai", 57 },
                    { 417, "Indaplovės", 57 },
                    { 418, "Kavos aparatai", 57 },
                    { 419, "Kondicionieriai", 57 },
                    { 420, "Kita", 57 },
                    { 421, "Fotoaparatai", 58 },
                    { 422, "Optiniai prietaisai", 58 },
                    { 423, "Paslaugos", 58 },
                    { 424, "Dalys, priedai", 58 },
                    { 425, "Kita", 58 },
                    { 426, "Dokumentų naikikliai", 59 },
                    { 427, "Įrišimo aparatai", 59 },
                    { 428, "Kasos aparatai", 59 },
                    { 429, "Kopijavimo aparatai", 59 },
                    { 430, "Laminavimo aparatai", 59 },
                    { 431, "Pjaustyklės", 59 },
                    { 432, "Prekybiniai baldai", 59 },
                    { 433, "Skaičiuotuvai", 59 },
                    { 434, "Spausdinimo mašinėlės", 59 },
                    { 435, "Kita", 59 },
                    { 436, "Įranga", 60 },
                    { 437, "Įrankiai", 60 },
                    { 438, "Technika", 60 },
                    { 439, "Kita", 60 },
                    { 440, "Dažymo įranga", 61 },
                    { 441, "Filtravimo, ventiliavimo įranga", 61 },
                    { 442, "Įrankiai", 61 },
                    { 443, "Maisto pramonės technika", 61 },
                    { 444, "Medienos apdirbimo įranga", 61 },
                    { 445, "Metalo apdirbimo įranga", 61 },
                    { 446, "Oro kompresoriai", 61 },
                    { 447, "Sandėliavimo įranga", 61 },
                    { 448, "Siuvimo technika", 61 },
                    { 449, "Šildymo, šaldymo įranga", 61 },
                    { 450, "Kita", 61 },
                    { 451, "Audio technika", 62 },
                    { 452, "Buitinė technika", 62 },
                    { 453, "Foto technika, optika", 62 },
                    { 454, "Sodo, miško technika", 62 },
                    { 455, "Transportavimas", 62 },
                    { 456, "Video technika", 62 },
                    { 457, "Nuoma", 62 },
                    { 458, "Kita", 62 },
                    { 459, "Kinas", 64 },
                    { 460, "Albumai", 64 },
                    { 461, "Grožinė literatūra", 64 },
                    { 462, "Mokslinė literatūra", 64 },
                    { 463, "Techninė literatūra", 64 },
                    { 464, "Literatūra užsienio kalba", 64 },
                    { 465, "Literatūra vaikams", 64 },
                    { 466, "Vadovėliai", 64 },
                    { 467, "Žodynai, enciklopedijos", 64 },
                    { 468, "Žurnalai", 64 },
                    { 469, "Dovanojamos knygos, žurnalai", 64 },
                    { 470, "Kita", 64 },
                    { 471, "Sporto inventorius", 65 },
                    { 472, "Sportinė avalynė", 65 },
                    { 473, "Sporto drabužiai", 65 },
                    { 474, "Sporto klubai", 65 },
                    { 475, "Žaidimai", 65 },
                    { 476, "Radijo valdomi modeliai", 65 },
                    { 477, "Dviračiai", 65 },
                    { 478, "Papildai", 65 },
                    { 479, "Sporto prekių, žaidimų nuoma", 65 },
                    { 480, "Kita", 65 }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
