using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace inkvBE.Migrations
{
    /// <inheritdoc />
    public partial class TypeSeeding2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "Types",
                columns: new string[] { "Id", "TypeName", "SubcategoryId" },
                values: new object[,]
                {
                    { 21, "Kita", 1 },
                    { 22, "Motociklai", 2 },
                    { 23, "Motoroleriai, mopedai", 2 },
                    { 24, "Kartingai", 2 },
                    { 25, "Keturračiai", 2 },
                    { 26, "Sniego motociklai", 2 },
                    { 27, "Apranga, šalmai, aksesuarai", 2 },
                    { 28, "Kita", 2 },
                    { 29, "Autobusai", 3 },
                    { 30, "Mikroautobusai", 3 },
                    { 31, "Prikabinami nameliai", 3 },
                    { 32, "Stacionarūs namukai, vagonėliai", 3 },
                    { 33, "Turistiniai automobiliai", 3 },
                    { 34, "Kita", 3 },
                    { 35, "Paspirtukai", 4 },
                    { 36, "BMX", 4 },
                    { 37, "Elektriniai dviračiai", 4 },
                    { 38, "Gravel, krosiniai dviračiai", 4 },
                    { 39, "Hibridiniai dviračiai", 4 },
                    { 40, "Kalnų dviračiai", 4 },
                    { 41, "Miesto dviračiai", 4 },
                    { 42, "Plento, sportiniai dviračiai", 4 },
                    { 43, "Sulankstomi dviračiai", 4 },
                    { 44, "Triračiai", 4 },
                    { 45, "Turistiniai dviračiai", 4 },
                    { 46, "Vaikiški dviračiai", 4 },
                    { 47, "Riedžiai", 4 },
                    { 48, "Velomobiliai", 4 },
                    { 49, "Aksesuarai", 4 },
                    { 50, "Dviračių laikikliai", 4 },
                    { 51, "Remontas", 4 },
                    { 52, "Dalys", 4 },
                    { 53, "Kėdutės, priekabos", 4 },
                    { 54, "Dviračių, paspirtukų nuoma", 4 },
                    { 55, "Kita", 4 },
                    { 56, "Autotraukiniai", 5 },
                    { 57, "Komun. ūkio transportas", 5 },
                    { 58, "Maisto ir gėrimų transportas", 5 },
                    { 59, "Miško ūkio technika", 5 },
                    { 60, "Sandėliavimo technika", 5 },
                    { 61, "Statybos ir kelių tiesimo technika", 5 },
                    { 62, "Statybos technikos priedai", 5 },
                    { 63, "Sunkvežimiai", 5 },
                    { 64, "Vilkikai", 5 },
                    { 65, "Priekabos", 5 },
                    { 66, "Spec. transporto nuoma", 5 },
                    { 67, "Kita", 5 },
                    { 68, "Baidarės, kanojos", 6 },
                    { 69, "Burlentės, banglentės", 6 },
                    { 70, "Jachtos", 6 },
                    { 71, "Katamaranai", 6 },
                    { 72, "Kateriai", 6 },
                    { 73, "Laivai", 6 },
                    { 74, "Valtys, plaustai, dviračiai", 6 },
                    { 75, "Vandens motociklai", 6 },
                    { 76, "Nuoma", 6 },
                    { 77, "Remontas", 6 },
                    { 78, "Varikliai", 6 },
                    { 79, "Dalys", 6 },
                    { 80, "Kita", 6 },
                    { 81, "Žemės ūkio technikos dalys", 7 },
                    { 82, "Daržovių nuėmimo, apdorojimo technika", 7 },
                    { 83, "Frezos", 7 },
                    { 84, "Grąžtai žemei", 7 },
                    { 85, "Grėbliai", 7 },
                    { 86, "Grūdų tvarkymo technika", 7 },
                    { 87, "Kombainai", 7 },
                    { 88, "Krautuvai", 7 },
                    { 89, "Kultivatoriai, akėčios", 7 },
                    { 90, "Mėšlo kratytuvai", 7 },
                    { 91, "Motoblokai", 7 },
                    { 92, "Pašarų ruošimo technika", 7 },
                    { 93, "Plūgai", 7 },
                    { 94, "Presai", 7 },
                    { 95, "Kita", 7 },
                    { 96, "Auto dalys", 8 },
                    { 97, "Akumuliatoriai, tepalai, autokosmetika", 8 },
                    { 98, "Alkotesteriai", 8 },
                    { 99, "Dviračių laikikliai", 8 },
                    { 100, "Garso, vaizdo aparatūra", 8 },
                    { 101, "Mikroautobusų dalys", 8 },
                    { 102, "Moto dalys", 8 },
                    { 103, "Padangos", 8 },
                    { 104, "Parkavimo sistemos", 8 },
                    { 105, "Priekabų, puspriekabių dalys", 8 },
                    { 106, "Ratlankiai", 8 },
                    { 107, "Servisų įranga, įrankiai", 8 },
                    { 108, "Kita", 8 },
                    { 109, "Apsaugos sistemų montavimas", 9 },
                    { 110, "Autoservisų įrangos aptarnavimas", 9 },
                    { 111, "Dujų įrangos montavimas", 9 },
                    { 112, "Keleivių vežimas", 9 },
                    { 113, "Krovinių gabenimas", 9 },
                    { 114, "Nuoma", 9 },
                    { 115, "Plovimo paslaugos", 9 },
                    { 116, "Remontas", 9 },
                    { 117, "Stiklų tonavimas, keitimas", 9 },
                    { 118, "Supirkimas", 9 },
                    { 119, "Šiukšlių, atliekų išvežimas", 9 },
                    { 120, "Tiuningas", 9 },
                    { 121, "Kita", 9 },
                    { 122, "Apdaila", 20 },
                    { 123, "Aplinkos tvarkymas", 20 },
                    { 124, "Apsaugos sistemos", 20 },
                    { 125, "Durys, langai, laiptai", 20 },
                    { 126, "Elektros instaliacija", 20 },
                    { 127, "Įrangos, įrankių nuoma", 20 },
                    { 128, "Kadastriniai matavimai", 20 },
                    { 129, "Projektavimas, dizainas", 20 },
                    { 130, "Santechnikos darbai", 20 },
                    { 131, "Saulės elektrinės įrengimas", 20 },
                    { 132, "Statybiniai darbai", 20 },
                    { 133, "Suvirinimo darbai", 20 },
                    { 134, "Šildymas, vėdinimas", 20 },
                    { 135, "Šiukšlių, atliekų išvežimas", 20 },
                    { 136, "Tvoros, vartai", 20 },
                    { 137, "Kita", 20 },
                    { 138, "Administratoriai", 22 },
                    { 139, "Apdailininkai", 22 },
                    { 140, "Apsaugos darbuotojai", 22 },
                    { 141, "Asistentai", 22 },
                    { 142, "Auklės, namų auklėtojai", 22 },
                    { 143, "Auto darbininkai", 22 },
                    { 144, "Barmenai, padavėjai", 22 },
                    { 145, "Brokeriai", 22 },
                    { 146, "Buhalteriai", 22 },
                    { 147, "Dažytojai", 22 },
                    { 148, "Dizaineriai", 22 },
                    { 149, "Elektrikai", 22 },
                    { 150, "Floristai", 22 },
                    { 151, "Gamybos darbuotojai", 22 },
                    { 152, "Gydytojai", 22 },
                    { 153, "Inžinieriai", 22 },
                    { 154, "IT specialistai", 22 },
                    { 155, "Kalviai, šaltkalviai-suvirintojai", 22 },
                    { 156, "Kirpėjai", 22 },
                    { 157, "Konsultantai", 22 },
                    { 158, "Kita", 22 },
                    { 159, "Administratoriai", 23 },
                    { 160, "Apdailininkai", 23 },
                    { 161, "Apsaugos darbuotojai", 23 },
                    { 162, "Architektai", 23 },
                    { 163, "Asistentai", 23 },
                    { 164, "Auklės, namų auklėtojai", 23 },
                    { 165, "Auto darbininkai", 23 },
                    { 166, "Barmenai, padavėjai", 23 },
                    { 167, "Biuro administratoriai", 23 },
                    { 168, "Brokeriai", 23 },
                    { 169, "Buhalteriai", 23 },
                    { 170, "Dažytojai", 23 },
                    { 171, "Dizaineriai", 23 },
                    { 172, "Ekspertai", 23 },
                    { 173, "Elektrikai", 23 },
                    { 174, "Gamybos darbuotojai", 23 },
                    { 175, "Inžinieriai", 23 },
                    { 176, "Kalviai, šaltkalviai-suvirintojai", 23 },
                    { 177, "Kompiuterių technikai", 23 },
                    { 178, "Konsultantai", 23 },
                    { 179, "Kita", 23 },
                    { 180, "Auskarai, tatuiravimas", 25 },
                    { 181, "Blakstienų priauginimas", 25 },
                    { 182, "Depiliacija", 25 },
                    { 183, "Gydymas, slauga", 25 },
                    { 184, "Kosmetologija", 25 },
                    { 185, "Manikiūras, pedikiūras", 25 },
                    { 186, "Masažas", 25 },
                    { 187, "Plaukų priežiūra", 25 },
                    { 188, "Soliariumas", 25 },
                    { 189, "Kita", 25 },
                    { 190, "Buhalterių kursai", 26 },
                    { 191, "Dailės pamokos", 26 },
                    { 192, "Grožio paslaugų kursai", 26 },
                    { 193, "Kalbų kursai", 26 },
                    { 194, "Kompiuterių kursai", 26 },
                    { 195, "Muzikos kursai", 26 },
                    { 196, "Savigynos kursai", 26 },
                    { 197, "Siuvimo, modeliavimo kursai", 26 },
                    { 198, "Vadybos kursai", 26 },
                    { 199, "Vairavimo kursai", 26 },
                    { 200, "Korepetitoriai", 26 },
                    { 201, "Rašto darbų konsultantai", 26 },
                    { 202, "Seminarai", 26 },
                    { 203, "Kita", 26 },
                    { 204, "Atributika, techninis aptarnavimas", 27 },
                    { 205, "Fotografai", 27 },
                    { 206, "Laidojimo paslaugos", 27 },
                    { 207, "Limuzinai, vestuvių transportas", 27 },
                    { 208, "Maitinimas", 27 },
                    { 209, "Muzikantai", 27 },
                    { 210, "Operatoriai", 27 },
                    { 211, "Renginių vedėjai, planuotojai", 27 },
                    { 212, "Šokėjai", 27 },
                    { 213, "Kita", 27 },
                    { 214, "Investicijos", 28 },
                    { 215, "Lombardo paslaugos", 28 },
                    { 216, "Partnerystės", 28 },
                    { 217, "Paskolos, kreditai", 28 },
                    { 218, "Steigimas, likvidavimas", 28 },
                    { 219, "Verslo pardavimas, franšizės", 28 },
                    { 220, "Kita", 28 },
                    { 221, "Web sprendimai", 29 },
                    { 222, "WWW svetainės", 29 },
                    { 223, "Augalai", 32 },
                    { 224, "Arkliai, žirgai", 32 },
                    { 225, "Elniniai", 32 },
                    { 226, "Gyvuliai", 32 },
                    { 227, "Graužikai", 32 },
                    { 228, "Katės", 32 },
                    { 229, "Paukščiai", 32 },
                    { 230, "Ropliai", 32 },
                    { 231, "Šeškai, fretkos", 32 },
                    { 232, "Šunys", 32 },
                    { 233, "Triušiai", 32 },
                    { 234, "Vabzdžiai", 32 },
                    { 235, "Voragyviai", 32 },
                    { 236, "Žuvys", 32 },
                    { 237, "Paslaugos", 32 },
                    { 238, "Pašarai", 32 },
                    { 239, "Prekės, reikmenys", 32 },
                    { 240, "Kita", 32 },
                    { 241, "Higienos priemonės", 33 },
                    { 242, "Įranga", 33 },
                    { 243, "Kosmetika", 33 },
                    { 244, "Vitaminai, papildai", 33 },
                    { 245, "Kita", 33 },
                    { 246, "Alaus atributika", 34 },
                    { 247, "Atvirutės", 34 },
                    { 248, "Banknotai", 34 },
                    { 249, "Kolekciniai modeliukai", 34 },
                    { 250, "Militaristika", 34 },
                    { 251, "Monetos", 34 },
                    { 252, "Nuotraukos", 34 },
                    { 253, "Ordinai, medaliai, ženkliukai", 34 },
                    { 254, "Pašto ženklai", 34 },
                    { 255, "Aksesuarai", 34 },
                    { 256, "Kita", 34 },
                    { 257, "Paslaugos", 35 },
                    { 258, "Daržovės", 35 },
                    { 259, "Gėrimai", 35 },
                    { 260, "Grybai", 35 },
                    { 261, "Grūdai, kruopos", 35 },
                    { 262, "Kiaušiniai", 35 },
                    { 263, "Konditeriniai gaminiai", 35 },
                    { 264, "Medus", 35 },
                    { 265, "Mėsa, mėsos produktai", 35 },
                    { 266, "Pieno produktai", 35 },
                    { 267, "Prieskoniai", 35 },
                    { 268, "Pusgaminiai", 35 },
                    { 269, "Riešutai", 35 },
                    { 270, "Uogos", 35 },
                    { 271, "Vaisiai", 35 },
                    { 272, "Žuvis, žuvies produktai", 35 },
                    { 273, "Kita", 35 },
                    { 274, "Buitinės talpyklos", 36 },
                    { 275, "Indai", 36 },
                    { 276, "Patalynė", 36 },
                    { 277, "Rankšluoščiai", 36 },
                    { 278, "Siuvimo, mezgimo reikmenys", 36 },
                    { 279, "Stalo įrankiai", 36 },
                    { 280, "Tualeto reikmenys", 36 },
                    { 281, "Valymo, plovimo reikmenys", 36 },
                    { 282, "Virtuvės reikmenys", 36 },
                    { 283, "Kita", 36 },
                    { 284, "Baldai", 37 },
                    { 285, "Ginklai", 37 },
                    { 286, "Indai, vazos", 37 },
                    { 287, "Interjero detalės", 37 },
                    { 288, "Knygos, kinas", 37 },
                    { 289, "Muzikos instrumentai", 37 },
                    { 290, "Stalo įrankiai", 37 },
                    { 291, "Šviestuvai", 37 },
                    { 292, "Technika", 37 },
                    { 293, "Kita", 37 },
                    { 294, "Dovanojama", 38 },
                    { 295, "Radiniai", 38 },
                    { 296, "Anglys", 39 },
                    { 297, "Briketai", 39 },
                    { 298, "Dujų balionai", 39 },
                    { 299, "Granulės", 39 },
                    { 300, "Malkos", 39 },
                    { 301, "Šildymo įranga", 39 },
                    { 302, "Kita", 39 },
                    { 303, "Ausinės", 42 },
                    { 304, "Daugiafunkciniai įrenginiai", 42 },
                    { 305, "Garso kolonėlės", 42 },
                    { 306, "Klaviatūros", 42 },
                    { 307, "Monitoriai", 42 },
                    { 308, "Pelės", 42 },
                    { 309, "Projektoriai", 42 },
                    { 310, "Skeneriai", 42 },
                    { 311, "Spausdintuvai", 42 },
                    { 312, "Web kameros", 42 },
                    { 313, "Žaidimų priedai", 42 },
                    { 314, "Kita", 42 },
                    { 315, "Nešiojamiems kompiuteriams", 43 },
                    { 316, "Stacionariems kompiuteriams", 43 },
                    { 317, "Kita", 43 },
                    { 318, "Baterijos, akumuliatoriai", 44 },
                    { 319, "Įkrovikliai", 44 },
                    { 320, "Adapteriai", 44 },
                    { 321, "Atminties kortelės", 44 },
                    { 322, "CD, DVD, Blu-ray diskai", 44 },
                    { 323, "HDD dėžutės", 44 },
                    { 324, "Išoriniai HDD", 44 },
                    { 325, "Kabeliai, jungtys", 44 },
                    { 326, "Krepšiai kompiuteriams", 44 },
                    { 327, "UPS (NMŠ)", 44 },
                    { 328, "USB atmintinės", 44 },
                    { 329, "Kita", 44 },
                    { 330, "Kompiuteriniai žaidimai", 45 },
                    { 331, "Antivirusinės programos", 45 },
                    { 332, "Apple programinė įranga", 45 },
                    { 333, "Biuro programinė įranga", 45 },
                    { 334, "Mokomosios programos", 45 },
                    { 335, "Operacinės sistemos", 45 },
                    { 336, "Techninė programinė įranga", 45 },
                    { 337, "Vaizdo apdorojimo programos", 45 },
                    { 338, "Kita", 45 },
                    { 339, "Belaidžio tinklo įranga", 46 },
                    { 340, "HUB", 46 },
                    { 341, "Maršrutizatoriai", 46 },
                    { 342, "Modemai", 46 },
                    { 343, "Switch", 46 },
                    { 344, "Aksesuarai, kabeliai", 46 },
                    { 345, "Kita", 46 },
                    { 346, "3D spausdinimas", 47 },
                    { 347, "Remontas", 47 },
                    { 348, "Spausdinimas, kopijavimas", 47 },
                    { 349, "Supirkimas", 47 },
                    { 350, "Kita", 47 }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
